#!/bin/bash
# A1 verifier. Runs in the SAME container as the agent (shared mode). Measures a
# BASELINE from the pristine sglang snapshot, then the AGENT's live (edited)
# sglang, both with the fixed canonical launch + benchmark commands, and gates
# on TTFT / throughput / accuracy improvements.
set -u

source /tests/bench_lib.sh

mkdir -p /logs/verifier

# Integrity gate: the pristine baseline snapshot must be byte-identical to the
# build-time state. The agent legitimately edits the LIVE tree
# (/sgl-workspace/sglang) but must not touch /opt/sglang-pristine — tampering
# there would let it slow the baseline and inflate its measured speedup. A
# MISSING manifest is a hard failure (an agent could have deleted it), not a
# warning. Regenerated bytecode is excluded from the manifest at build time.
if [ ! -f /opt/sglang-pristine.sha256 ]; then
  echo "[verifier] FATAL: /opt/sglang-pristine.sha256 manifest missing — cannot verify baseline integrity"
  echo 0 > /logs/verifier/reward.txt; exit 0
fi
if ! sha256sum --quiet --check /opt/sglang-pristine.sha256 > /tmp/pristine_check.txt 2>&1; then
  echo "[verifier] pristine baseline integrity check FAILED (snapshot was modified):"
  grep -vE "OK$" /tmp/pristine_check.txt | head -20
  cp /tmp/pristine_check.txt /logs/verifier/ 2>/dev/null || true
  echo 0 > /logs/verifier/reward.txt; exit 0
fi
echo "[verifier] pristine baseline integrity verified"

# 1) Baseline: pristine sglang via PYTHONPATH override of the editable install.
measure_variant baseline /opt/sglang-pristine /tmp/a1_baseline.json

# 2) Agent: the live (possibly edited) editable tree.
measure_variant agent "" /tmp/a1_agent.json

cp /tmp/a1_baseline.json /tmp/a1_agent.json /logs/verifier/ 2>/dev/null || true

# 3) Gate.
/opt/venv/bin/python -m pip install --quiet --no-input pytest==8.4.1 pytest-json-ctrf==0.3.5
/opt/venv/bin/python -m pytest --ctrf /logs/verifier/ctrf.json /tests/test_outputs.py -rA

if [ $? -eq 0 ]; then
  echo 1 > /logs/verifier/reward.txt
else
  echo 0 > /logs/verifier/reward.txt
fi
